// Generated by lesson_3/build_running_examples_data.py — do not edit by hand.
window.RUNNING_EXAMPLES = {
 "meta": {
  "dataset": "Bitext Customer Support, 2000-ticket cached subset",
  "e2_model": "TF-IDF + logistic regression",
  "e4_model": "k-means (k=6) on TF-IDF, nearest-centroid matching",
  "llm_model": "openai/gpt-5.2"
 },
 "sentences": [
  "how do I get a refund for my last payment?",
  "I want to close my account and delete my personal data",
  "where is my package? it was supposed to arrive on Monday",
  "can I change the shipping address on order 4211?",
  "my card was charged twice for the same order",
  "I returned the shoes two weeks ago and still have no money back",
  "the promo code didn't work at checkout",
  "I forgot my password and the reset email never arrives"
 ],
 "e2": [
  {
   "label": "REFUND",
   "confidence": 0.69
  },
  {
   "label": "ACCOUNT",
   "confidence": 0.93
  },
  {
   "label": "DELIVERY",
   "confidence": 0.48
  },
  {
   "label": "DELIVERY",
   "confidence": 0.35
  },
  {
   "label": "ACCOUNT",
   "confidence": 0.33
  },
  {
   "label": "REFUND",
   "confidence": 0.73
  },
  {
   "label": "ACCOUNT",
   "confidence": 0.67
  },
  {
   "label": "ACCOUNT",
   "confidence": 0.82
  }
 ],
 "e3": [
  {
   "label": "REFUND"
  },
  {
   "label": "ACCOUNT"
  },
  {
   "label": "DELIVERY"
  },
  {
   "label": "DELIVERY"
  },
  {
   "label": "PAYMENT"
  },
  {
   "label": "REFUND"
  },
  {
   "label": "ORDER"
  },
  {
   "label": "ACCOUNT"
  }
 ],
 "e4": {
  "clusters": [
   {
    "idx": 0,
    "size": 102,
    "top_terms": [
     "account",
     "type",
     "need",
     "use",
     "change",
     "know"
    ],
    "samples": [
     "problem with creatingmy {{Account Type}} account",
     "i dont know how to change to the {{Account Type}} account",
     "correcting data on {{Account Type}} accoujnt"
    ],
    "name": "Change account type",
    "resolution": "Explain the account tiers and send the self-service link to switch account type."
   },
   {
    "idx": 1,
    "size": 362,
    "top_terms": [
     "order",
     "number",
     "purchase",
     "help",
     "cancel",
     "status"
    ],
    "samples": [
     "how canI change order {{Order Number}}?",
     "can  uhelp me canceling order {{Order Number}}",
     "help  me canceling purchase {{Order Number}}"
    ],
    "name": "Order changes & cancellations",
    "resolution": "Send the order-management link to view status, edit, or cancel; escalate if already shipped."
   },
   {
    "idx": 2,
    "size": 266,
    "top_terms": [
     "payment",
     "options",
     "methods",
     "help",
     "check",
     "modalities"
    ],
    "samples": [
     "help me to see your available payment modalities",
     "where to check what methods for delivery are available?",
     "I need help seeing what options for delivery you offer"
    ],
    "name": "Payment & delivery options",
    "resolution": "Reply with the accepted payment methods and the delivery options for the customer's country."
   },
   {
    "idx": 3,
    "size": 169,
    "top_terms": [
     "refund",
     "expect",
     "soon",
     "symbol",
     "currency",
     "waiting"
    ],
    "samples": [
     "refunding {{Currency Symbol}}{{Refund Amount}}",
     "can you help me seeing in what cases can I request a refund?",
     "how long till I obtain a refund of money?"
    ],
    "name": "Refund status & policy",
    "resolution": "Share the refund-policy page, look up the refund case, and give the expected processing time."
   },
   {
    "idx": 4,
    "size": 780,
    "top_terms": [
     "help",
     "need",
     "money",
     "know",
     "want",
     "assistance"
    ],
    "samples": [
     "I do not know how I could ask for goddamn refunds",
     "assistance to check youe money back guarantee",
     "I cannot remember my user key, I want to reset it"
    ],
    "name": "Catch-all: unclear requests",
    "resolution": "No single resolution — route to a human agent."
   },
   {
    "idx": 5,
    "size": 321,
    "top_terms": [
     "account",
     "category",
     "standard",
     "pro",
     "gold",
     "information"
    ],
    "samples": [
     "what do i need to do to change to the gold account",
     "where can i fiond information about a pro account removal",
     "problem with premium account deletions"
    ],
    "name": "Premium accounts & deletion",
    "resolution": "Verify identity, then process the account change or deletion and confirm by email."
   }
  ],
  "matched": [
   3,
   5,
   4,
   4,
   4,
   4,
   4,
   4
  ]
 },
 "e5": [
  {
   "title": "Support chat",
   "text": "Customer: I was charged twice for order #4211 — I'd like one of the charges refunded. Agent: Let me check... I can see the duplicate charge on the 12th. I've opened refund case R-812 for you; the payment team reviews these within 3 business days and you'll get an email as soon as it's approved. Customer: OK. Will the refund go back to the same card? Agent: Yes, always to the original payment method.",
   "summary": "Customer reports a duplicate charge for order #4211 and needs one charge refunded; refund case R-812 is opened for payment team review (3 business days) and should be returned to the original card."
  },
  {
   "title": "Incident note",
   "text": "Between 09:14 and 09:52 UTC the checkout service returned errors for roughly 8% of requests. The trigger was a config push that lowered the payment-gateway timeout from 3s to 300ms; retries then saturated the gateway. Rolling back the config restored normal error rates by 09:55. No double charges were observed, but 214 carts were abandoned during the window. Follow-up: add a canary stage for gateway config and an alert on timeout-related error spikes.",
   "summary": "Investigate and remediate the 09:14–09:52 UTC checkout errors caused by a config change reducing the payment-gateway timeout to 300ms (rollback done), confirm no double charges and review the 214 abandoned carts, then implement a canary stage for gateway config changes and an alert for timeout-related error spikes."
  },
  {
   "title": "Customer email",
   "text": "Hi, sorry to bother you again, I wrote last week about my order — the blue lamp, I think the order number is 5590 or maybe 5990, I can't find the email right now. Anyway it arrived but the shade is cracked on one side, you can't see it from the front but still. I don't necessarily want to send it back because we already installed it, honestly I'd be happy with a partial refund or a replacement shade if you have one. Let me know what's possible. Best, Marta",
   "summary": "Customer Marta reports her blue lamp order (possibly #5590 or #5990) arrived with a cracked shade after installation and requests either a partial refund or a replacement shade without returning the lamp."
  }
 ]
};
